# Generated by Django 3.1.7 on 2021-04-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0002_auto_20210425_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('picture_img', models.ImageField(upload_to='filtered_images/')),
            ],
        ),
    ]
