# Generated by Django 3.1.7 on 2021-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0003_filteredpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteredpicture',
            name='picture_img',
        ),
        migrations.AddField(
            model_name='filteredpicture',
            name='path',
            field=models.CharField(default='filler', max_length=50, unique=True),
        ),
    ]
