# Generated by Django 3.1.7 on 2021-04-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0004_auto_20210426_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='assoc_url',
            field=models.CharField(default='filler', max_length=50, unique=True),
        ),
    ]
