# Generated by Django 3.1.7 on 2021-04-27 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0007_filteredpicture_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='filtered_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
