# Generated by Django 3.1.7 on 2021-04-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainproject', '0008_picture_filtered_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='assoc_url',
        ),
        migrations.AddField(
            model_name='picture',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
